Theory of natural numbers
harp-project/AML-Formalization pull request #319
Opened 2022-11-12 17:42 UTC by Bxil

- Predicate propagation
- Membership symbol for arbitrary pattern on the left
- Peano induction

2022-11-14 16:43 UTC, berpeti requested changes
I added my comments to the code. I marked a number of lemmas to be moved to `Definedness_ProofSystem.v`, however, lemmas containing predicate and functional patterns could also be moved to a new file which is specific to express reasoning about patterns of first-order logic.

2022-11-14 16:43 UTC, berpeti commented on matching-logic/src/Theories/Definedness_ProofSystem.v
> +Lemma bott_and {Σ : Signature} Γ ϕ :
I suggest moving this to `ProofMode_propositional.v`.

2022-11-14 16:43 UTC, berpeti commented on matching-logic/src/Theories/Definedness_ProofSystem.v
> +Lemma top_and {Σ : Signature} Γ ϕ :
I suggest moving this to `ProofMode_propositional.v`. Another observation is that you do not need to leave the proofmode, if you use `mlAdd`.

2022-11-14 16:43 UTC, berpeti commented on matching-logic/src/Theories/Unification.v
> +  Lemma membership_imp_equal Γ φ φ' :
I suggest removing this lemma, as I mentioned before.

2022-11-15 17:51 UTC, h0nzZik commented
I quickly went over the code, and do agree with Peter on all points. I have no other comments so far.

2022-11-15 17:54 UTC, h0nzZik commented
There already is a file for for FO reasoning without equality, so this new file would be for FO with equality.

2022-11-16 10:48 UTC, berpeti commented on matching-logic/src/Theories/Nat.v
> +Lemma ex_sort_impl_ex {Σ : Signature} {syntax : Syntax} Γ ϕ s :
Yes, I see. I did not recognize the notation of sorted quantification.

2022-11-16 10:51 UTC, berpeti commented on matching-logic/src/Theories/Definedness_ProofSystem.v
> +Lemma top_and {Σ : Signature} Γ ϕ :
Then the other option is to use `mlAssert`, and `aapply`. However, I am happy with this solution too, it was a suggestion so that the proof mode is not left.

2022-11-16 11:01 UTC, berpeti requested changes
I also suggest using a different name instead of `FOEquality.v`, that fits the current names. E.g. `FOEquality_ProofSystem.v`.

2022-11-17 08:19 UTC, berpeti approved these changes

2022-11-17 08:39 UTC, merged