Nat theory
harp-project/AML-Formalization pull request #425
Opened 2024-02-20 12:37 UTC by adilido99

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +        → mu_free φ
Please be consistent with the formatting to the other files (e.g., like in `Bool_ProofSystem.v`, `Definedness_ProofSystem.v`). Use `->` for the implication, do not use an additional indentation for each hypothesis please.

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +        → mu_free φ
This also applies to the following theorems, lemmas.

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem unnamed:
This theorem should be renamed. How about `mu_free_evar_quantify`?

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem exists_functional_subst_meta:
The theorems which are not specific to bools, but are about `is_functional` patterns: please move these into `FOEquality_ProofSystem.v` for now. In a later phase, we should move all such theorems into a separate file.

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +        1:{ case_match. all:reflexivity. }
If you use the same idea for all of the goals, just use `all: case_match; reflexivity` please. If the idea is the same for most of them, use the `try` tactic to shorten this part.

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem  something_v2:
Yes, please change the name. For example, `proved_membership_functional`?

2024-02-23 15:38 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem  something_v3:
If you do not use this one, please delete it.

2024-03-26 16:26 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +Require Import MatchingLogic.Theories.DeductionTheorem.
Why are these new imports needed? What failed without them?

2024-03-26 16:31 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem  provable_iff_top:
Move this to `ProofMode/Propositional.v` please.

2024-03-26 16:31 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem  patt_and_id_r:
Move this to `ProofMode/Propositional.v` please.

2024-03-26 16:31 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem proved_membership_functional:
Move this to `FOEquality_ProofSystem.v` please.

2024-03-26 16:31 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Theorem proved_membership_functional_meta:
Move this to `FOEquality_ProofSystem.v` please.

2024-03-26 16:31 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +  Lemma Svar_subst (Γ : Theory) (ϕ ψ : Pattern) (X : svar)  (i : ProofInfo)
Why is this here? Is this a new theorem, or did you just check it, and forgot to remove it?

2024-03-26 16:31 UTC, berpeti commented on matching-logic/src/Theories/Nat_ProofSystem.v
> +    Search patt_exists derives_using.
In general, if a proof is ready, please remove all `Search`, `Check`, `About`, `Compute` and `Print` commands.

2024-05-06 09:56 UTC, adilido99 commented
All comments are resolved, ready to merge

2024-05-07 12:03 UTC, berpeti requested changes

2024-05-07 12:03 UTC, berpeti commented on matching-logic/src/Experimental/Nat_ProofSystem.v
> +  Theorem t1:
Please, rename this to `membership_exists_subst`

2024-05-09 09:19 UTC, adilido99 commented
chnages made

2024-05-09 14:57 UTC, berpeti approved these changes

2024-05-09 14:57 UTC, merged