Product sort theory
harp-project/AML-Formalization pull request #429
Opened 2024-04-25 12:05 UTC by adilido99

2024-05-03 13:33 UTC, berpeti requested changes

2024-05-03 13:33 UTC, berpeti commented on matching-logic/src/Theories/ProductSort.v
> +    Notation "'mlProd' '(' s1 ',' s2 ')'"
These notations should be preferred to `Local Notation`s, since those depend on the context. Please, rephrase them such that they look similar! For example, the notation for pairs could be `(phi1 : s1, phi2 : s2)`, if that works (instead of `:`, you could use `\Colon`). For projections, I would vote for `(phi).mlProjL(s1, s2)`. This way, I hope, we can avoid duplicating notations.

2024-05-03 13:33 UTC, berpeti commented on matching-logic/src/Theories/ProductSort_ProofSystem.v
> +    Local Notation "'(' phi1 ',ml' phi2 ')'" :=
If you fix the notations, hopefully, these won't be needed anymore, and you can use the notations defined above, inside the `Notations` module.

2024-05-03 13:33 UTC, berpeti commented on matching-logic/src/Theories/ProductSort_ProofSystem.v
> +    Lemma use_productsort_axiom ax Γ  :
Indentation is wrong here.

2024-05-06 14:20 UTC, adilido99 commented
changes done, ready to merge

2024-05-07 11:50 UTC, berpeti approved these changes

2024-05-07 11:51 UTC, merged