Sum sort theory
harp-project/AML-Formalization pull request #430
Opened 2024-04-29 08:25 UTC by adilido99

the following theorems need to be named and moved: t1, t2, unnamed, unnamed_1
the admits are as follows: t3, membership_axiom_v1/v2

2024-05-06 15:20 UTC, adilido99 commented
changes resolved, ready to merge :)

2024-05-07 11:46 UTC, berpeti requested changes

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +  Theorem t1:
Please, rename this theorem, and move it to `Definedness_ProofSystem.v`. My suggestion for the name: `subset_iff_eq`.

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +   Theorem t2:
Please, rename this theorem, and move it to `Definedness_ProofSystem.v`. My suggestion for the name: `subset_disj`.

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +   Theorem  provable_iff_top:
Move this theorem to `ProofMode/Propositional.v`

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +  Theorem  patt_and_id_r:
Move this theorem to ProofMode/Propositional.v

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +    Qed.
Replace `Qed`-s with `Defined` everywhere, please.

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +  Theorem proved_membership_functional:
Please, move this theorem to `FOEquality_ProofSystem.v`

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +  Theorem unnamaed:
Rename this theorem please, and move it into `Definedness_ProofSystem.v`. My name suggestion is `total_iff_top`.

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +  Theorem unnamaed_1:
Move this please into `Sorts_ProofSystem.v`, and rename it, for example to `top_includes_everything`.

2024-05-07 11:46 UTC, berpeti commented on matching-logic/src/Experimental/SumSort_ProofSystem.v
> +  Theorem t3:
Rename this to `subseteq_iff_membership`

2024-05-10 11:06 UTC, berpeti approved these changes

2024-05-10 11:06 UTC, merged