Extend `mlRewriteBy` notation
harp-project/AML-Formalization pull request #441
Opened 2024-11-12 03:12 UTC by Thrithralas

Adds `<-`, `->` and `in` notation support for the mlRewriteBy tactic.

- `mlRewriteBy -> ...` works the same as `mlRewriteBy`, it's just for parity.
- `mlRewriteBy <- ...` applies the proof the other way around
- `mlRewriteBy ... in H` applies the proof on a hypothesis instead of the goal. A `<-` version of this exists as well.

I added a local test to demonstrate the changes.

There is an issue which I'm not sure how to fix: `mlRewriteBy ... in H` applies the proof on the goal if the hypothesis does not have enough occurrences of the LHS of the proof. Me and @Engreyight  tried to experiment with using `mlAssert` to construct a new hypothesis, but we couldn't find a way to compute the type of the new expression. Another potential solution is checking if `H` has enough matching subexpressions and failing if it doesn't, but I'm not sure how to do this either.

2024-11-12 12:19 UTC, berpeti requested changes

2024-11-12 12:19 UTC, berpeti commented on matching-logic/src/Theories/Definedness_ProofSystem.v
> +Local Example mlRewriteBy_test {Σ : Signature} {syntax : Syntax} Γ ϕ ψ :
Please, can you give more examples of using only `in` (without the `<-`) and using only `<-` (without `in`)? For potential revision in the future, we want to cover all behaviours with unit tests.

2024-11-12 18:05 UTC, Thrithralas commented on matching-logic/src/Theories/Definedness_ProofSystem.v
> +Local Example mlRewriteBy_test {Σ : Signature} {syntax : Syntax} Γ ϕ ψ :
I added a test for each of those cases

2024-11-13 08:18 UTC, berpeti approved these changes

2024-11-13 08:19 UTC, merged